// @cyberdyne/dao-contracts — frontend integration entry point.
//
// Consumers:
//   import {addresses, getAbi} from "@cyberdyne/dao-contracts";
//   const {osx, external} = addresses[chainId];
//   const payrollAbi = getAbi("PayrollPlugin");
//
// addresses.json is the build artifact emitted by scripts/build-addresses.js.
// ABIs live one per file under frontend-abi/, emitted by scripts/export-abis.js.
// Both are regenerated by `npm run build:package`.

const fs = require("fs");
const path = require("path");

const addresses = require("./addresses.json");

function getAbi(contractName) {
  const file = path.join(__dirname, "frontend-abi", `${contractName}.json`);
  if (!fs.existsSync(file)) {
    throw new Error(
      `ABI not found for "${contractName}". Run \`npm run build:abi\` in the contracts repo.`
    );
  }
  return JSON.parse(fs.readFileSync(file, "utf8")).abi;
}

function listAbis() {
  const dir = path.join(__dirname, "frontend-abi");
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir).filter((f) => f.endsWith(".json")).map((f) => f.replace(/\.json$/, ""));
}

module.exports = {addresses, getAbi, listAbis};
